### ISSUE TITLE
FIX5.0 package generation

### ISSUE THREAD

**Issue by blerstt** [arthurlm/quickfix-rs#13]
Hello, can you please provide information how to generate FIX5.0 package? I'm trying to generate it from spec provided by Coinbase here: [link](https://docs.cloud.coinbase.com/exchange/docs/fix-downloads)

**Comment by arthurlm** [comment]
Just to keep you updated:

1. I have updated my code and successfully generated the package for FIX 5.0 Market Data Gateway.
   I am confident in the changed I have made so the generated code should be good...
   If there is something wrong, do not hesitate to make a PR to fix it.
3. I have updated the example so 2 sessions are created (1 for order entry + 1 for market data)
4. I have renamed the `coinbase-fix42` crate to `coinbase-fix42-order-entry` (so crate names are now more clear)

What is still ongoing and blocked:

- I got a login permission failed when trying to log on the coinbase sandbox (I have reach CB support for this but it can take several days to have a response for this).
- I will add a new example when login issue is fixed.

**Comment by arthurlm** [comment]
I have talk with coinbase support.
As I was expecting, FIX MD is reserved for Institutional clients.
This is why, I am getting an  `INVALID_PERMISSION` error code when logging in.

So, I do not have any way to test the generated code.

I am pretty confident about it's quality, this is why I have merge #14.
However I cannot tell you if it is production ready or not. You will have to test this on your own.

I am closing this issue because I cannot do anything more.
I also update the FAQ / doc of this repository.

If you find anything more, feel free to reopen this issue / create new issue / new PR.
